server:
  port: 8070
spring:
  sql:
    init:
      mode: always
      continue-on-error: true
  servlet:
    multipart:
      enabled: true #Allow multipart in http
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/cloudstorage
    username: root
    password: password
logging:
    level:
      org:
        springframework:
          security: debug
          web: debug
jwt:
  secret:
    access: 8dfbf1c431968a3841fb99d6c3216b1d436a89b3f9d228002b65a4876c5c9663 #Secret key for generation of tokens
error:
    id:
      leftlimit: 48 #Paramters for random generation
      rightlimit: 57
      lenght: 6
files:
  path: d:/Users/vlad/Documents/Code/CloudStorage/FilesFolder #Folder for files
