###
//Аутентификация с получением токена: пользватель корректен, пароль некорректный
POST http://localhost:8070/login
Content-Type: application/json

{
  "login": "ivanov@mail.ru",
  "password": "111111"
}


###
//Получение списка файлов (скопировать и вставить токен после аутентификации)
GET http://localhost:8070/list?limit=3
Content-Type: application/json
Auth-Token: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpdmFub3ZAbWFpbC5ydSIsImlhdCI6MTY4ODM5MzQ3NiwiZXhwIjoxNjg4Mzk0NDc3fQ.CnzDEzrlIpeRUZy0N7_V3vo-gX9He_DST5tuGtplDEk


###
//Аутентификация с получением токена: пользватель корректен, пароль некорректный
POST http://localhost:8070/login
Content-Type: application/json

{
"login": "ivanov@mail.ru",
"password": "222222"
}


###
//Аутентификация с получением токена: пользватель некорректный, пароль некорректный
POST http://localhost:8070/login
Content-Type: application/json

{
  "login": "kukin@mail.ru",
  "password": "222222"
}

###
//Логаут неавторизованного юзера (скопировать и вставить токен после аутентификации)
POST http://localhost:8070/logout
Auth-Token: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpdmFub3ZAbWFpbC5ydSIsImlhdCI6MTY4ODM5MzQ3NiwiZXhwIjoxNjg4Mzk0NDc3fQ.CnzDEzrlIpeRUZy0N7_V3vo-gX9He_DST5tuGtplDEk

###
//Переименование файла: заменить токен после логина, создать файл и выполнить тест
PUT http://localhost:8070/file?filename=sourceTestFile.txt
Content-Type: application/json
Auth-Token: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpdmFub3ZAbWFpbC5ydSIsImlhdCI6MTY4ODQwOTYxMywiZXhwIjoxNjg4NDEwNjE0fQ.cMFIhVZ_bArLzwJfVPLGDCxKEyF2-czK72qru2Vqpdw

{
  "filename": "newNameOfFile.txt"
}

###
//Удаление файла: заменить токен посел логина, созать файл и выполнить тест
DELETE http://localhost:8070/file?filename=newNameOfFile.txt
Auth-Token: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpdmFub3ZAbWFpbC5ydSIsImlhdCI6MTY4ODQwOTYxMywiZXhwIjoxNjg4NDEwNjE0fQ.cMFIhVZ_bArLzwJfVPLGDCxKEyF2-czK72qru2Vqpdw
